# Generated by Django 5.1.2 on 2024-11-07 16:29

import artgallery.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20, validators=[artgallery.models.numberValidator, django.core.validators.MinLengthValidator(8)])),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(null=True, upload_to='gallery_profile/')),
                ('address', models.TextField(blank=True, default='')),
                ('contact', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_id', models.IntegerField(default=0)),
                ('target_index', models.IntegerField(default=0)),
                ('target_image', models.ImageField(null=True, upload_to='target_images/')),
                ('target_data', models.JSONField(null=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('audio', models.FileField(null=True, upload_to='audios/')),
                ('audio_name', models.TextField(blank=True)),
                ('augmented_video', models.FileField(null=True, upload_to='augmented_images_or_videos/')),
                ('extra_video', models.FileField(null=True, upload_to='extra_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='TargetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='target_file')),
            ],
        ),
    ]
